### ISSUE TITLE
[feature] Allow specification for Notes slide

### ISSUE THREAD

**Issue by liteman** [MartinPacker/md2pptx#83] opened 2021-07-18 12:55 UTC
Feature Request:
Allow specification for paragraph(s) to be added to the corresponding Notes slide.  Maybe with the blockquote `>` markdown character?  One `>` per paragraph in notes?

**Comment by MartinPacker** [comment] 2021-07-18 14:29
Well, today paragraph text buys you slide notes not note slides.

1) I'm hoping that's still working - as I haven't tested it in a while.

2) I suppose I could make it an option to create Notes slides - an option enabled via metadata. These would probably have the previous slide's title - with "Notes" appended. Also they would be bullet-free, like the Abstract slide is.

Let me know what you think. This won't get done immediately, but I'm open to ideas.

**Comment by liteman** [comment] 2021-07-18 15:59
Slide notes is what I'm after actually. I must have misunderstood the reference in python-pptx. 

How would I specify slide notes on a content slide? 

I've tried a blank line after the bullets  and I tried a paragraph tag `<p></p>`    -- neither seemed to have any effect

**Comment by MartinPacker** [comment] 2021-07-18 16:46
You don't need to to do paragraph tags; Just text after the bulleted list should work. Paragraphs should be as Markdown would have them. The idea here was that if you threw the same deck through a **real** Markdown processor you'd get the bullets and underneath the notes as paragraphs.

Sounds like this isn't working in md2pptx; I'll have to investigate. As I said, I haven't tested slide notes in a long time - as I haven't used them myself. Can you check if it's just the final slide's notes that don't appear? Or also previous slides' notes that don't.

And I'll keep the idea of notes slides on the back burner. I know - from the example of abstract slides how to make them appear.

**Comment by MartinPacker** [comment] 2021-07-19 09:51
I can confirm slide notes is broken. Now to figure out why.

**Comment by MartinPacker** [comment] 2021-07-19 10:43
So slide notes is repaired - and enhanced to translate eg `&percnt;` into `%`. Slide note creation is refactored into `createSlideNotes(slide, notes_text)` - which makes any future enhancements easier.

There's 1 bug before I push: For a Section or Title slide the notes also appear on the slide itself. Will pursue.

(It's actually possible I'll use slide notes in an upcoming presentation - because I'm developing the slide deck with a friend and we don't know each other's stuff all that well.)

**Comment by MartinPacker** [comment] 2021-07-19 15:23
Pushed. Documentation to follow.

**Comment by MartinPacker** [comment] 2021-07-19 16:03
RIght now slide notes can't contain active hyperlinks. I've opened a [separate issue for this](https://github.com/MartinPacker/md2pptx/issues/84).

**Comment by MartinPacker** [comment] 2021-07-19 16:20
Docs done and pushed. I'd like to fix [Issue 84](https://github.com/MartinPacker/md2pptx/issues/84) and any bugs from this before releasing 2.2.1 and closing this.

**Comment by MartinPacker** [comment] 2021-07-19 19:28
And [Issue 84](https://github.com/MartinPacker/md2pptx/issues/84) is now fixed. So ready to ship.

**Comment by MartinPacker** [comment] 2021-07-19 19:32
Fixed in v2.2.1.

**Closed by MartinPacker** 2021-07-19 19:32 UTC
