### ISSUE TITLE
Latin character í (Latin small letter i with acute) is displayed with errors

### ISSUE THREAD

**Issue by dariovasconcelos** [MartinPacker/md2pptx#161] opened 2024-07-03 17:33 UTC
All accentuated characters work correctly with the exception of "í", which generates a ">" on the final PPT
![CleanShot 2024-07-03 at 11 33 44@2x](https://github.com/MartinPacker/md2pptx/assets/156577/001e0f77-e1eb-4890-b1b5-67fc814b2fa0)

**Comment by MartinPacker** [comment] 2024-07-14 15:58
I think I might've fixed this. This is similar to the Danish character problem I encountered.

Can you try 5.0.1 - when I release it in a few minutes and see if the problem is still there?

Technical explanation: I was using high 8-bit chars as tokens. Now I'm using "guaranteed unused" high 16-bit Unicode codepoints instead.

Thanks!

(And sorry for taking a few days to notice your Issue.)

**Comment by dariovasconcelos** [comment] 2024-07-17 18:08
Thanks! But it's giving me the same problem :(

This is my output:

md2pptx Markdown To Powerpoint Converter 5.0.1 14 July, 2024
============================================================

Open source project: https://github.com/MartinPacker/md2pptx

External Dependencies:

  Python: 3.11.4
  python-pptx: 0.6.23
  Pillow: 10.4.0
  CairoSVG: Not Installed
  graphviz: Not Installed

Internal Dependencies:

  funnel: 0.1
  runPython: 0.2


----------------

My file is UTF-8 with Unicode: 
ReporteAssessment.md: Unicode text, UTF-8 text

The strange thing about this issue is that most accentuated characters work, only í doesn't

Thanks again!

**Comment by MartinPacker** [comment] 2024-07-18 08:37
Thank you. Do you have a Unicode code point for it. That will help me investigate.

**Comment by chutianshu1981** [comment] 2024-07-23 04:08
I encountered the same problem when using Simplified Chinese. I solved it by changing the 4924th line of code in md2pptx
`
with input_path.open(mode='r', encoding='utf-8') as file:
`

**Comment by MartinPacker** [comment] 2024-07-23 07:31
Thank you. We will need to test such a change extensively - to make sure it doesn't muck anything else up.

**Comment by MartinPacker** [comment] 2024-07-25 08:06
So, I've run this through 2 (not terribly challenging) presentations and it works.

So please test with the commit I just made (5.0.1+ 25 July when you run it.)

**Comment by MartinPacker** [comment] 2024-07-26 17:27
Shipped in [v5.0.2](https://github.com/MartinPacker/md2pptx/releases/tag/v5.0.2). Keeping this open for a while - in case there are regressions.

**Comment by MartinPacker** [comment] 2024-08-05 13:43
Closing. Feel free to reopen.

**Closed by MartinPacker** 2024-08-05 13:43 UTC
Labels: bug
